apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: campuscare
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: campuscare-helpdesk
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
